[build]
  command = "npm run build"
  publish = ".vuepress/dist/"
[[redirects]]
  from = "https://nonotw.com/*"
  to = "https://blog.nonotw.com/:splat"
[[redirects]]
  from = "https://nonotw.netlify.com/*"
  to = "https://blog.nonotw.com/:splat"
